DP-1534 : Feature - secure ros tools endpoint
MOV-AI/containers-haproxy pull request #47
Opened 2024-05-27 22:59 UTC by AlexFernandes-MOVAI

Modify HAPROXY configuration to:
- expose the ros-tools endpoint on https://robot_name/ros-tools
- generate certificates on startup
- create script to generate client certificates
- allow certificates verification using dedicated certificates and env vars for all frontend: https, ros-tools, redis-master

---
- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-05-28 12:50 UTC, mariana-dias-alves commented
With solution 2.3.1-106 and a built local container got:
![image](https://github.com/MOV-AI/containers-haproxy/assets/139454338/90c27e5c-e522-414c-b9e5-e8db24d8ffce)

2024-05-28 12:54 UTC, mariana-dias-alves requested changes
```
Error response

Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI. 
```

2024-05-29 14:45 UTC, AlexFernandes-MOVAI commented
> ```
> Error response
> 
> Error code 404.
> 
> Message: File not found.
> 
> Error code explanation: 404 = Nothing matches the given URI. 
> ```

this is due to certificate verification being enabled

2024-05-29 14:50 UTC, mariana-dias-alves submitted a review, later dismissed

2024-05-29 14:57 UTC, mariana-dias-alves approved these changes

2024-05-29 14:57 UTC, merged